# Generated by Django 3.2.6 on 2021-10-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shortnote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('status', models.CharField(choices=[('impoertant', (('color', 'rgb(220 53 69 / 10%)'), ('text', '<i class="fad fa-exclamation-circle"></i> important'), ('class', 'text-danger'))), ('warning', (('color', 'rgb(255 193 7 / 10%)'), ('text', '<i class="fad exclamation-triangle"></i> warning'), ('class', 'text-warning'))), ('note', (('color', 'rgb(13 110 253 / 10%)'), ('text', '<i class="fad fa-quote-left"></i> note'), ('class', 'text-primary')))], max_length=1000)),
                ('creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
