# Generated by Django 3.2.6 on 2021-10-17 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('write', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortnote',
            name='status',
        ),
    ]
