# Generated by Django 3.2.6 on 2021-10-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('write', '0002_remove_shortnote_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortnote',
            name='status',
            field=models.CharField(choices=[('impoertant', 'impoertant'), ('warning', 'warning'), ('note', 'note'), ('success', 'success')], default='', max_length=1000),
        ),
    ]
