# Generated by Django 3.2.6 on 2021-10-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('write', '0005_alter_shortnote_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortnote',
            name='pin',
            field=models.BooleanField(default=False),
        ),
    ]
